# Generated by Django 3.0.6 on 2020-05-22 07:41

import builtins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=140)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('actors', models.CharField(max_length=240)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(max_length=140)),
                ('release_date', models.DateField()),
                ('category', models.CharField(choices=[('HW', 'Hollywood'), ('BW', 'Bollywood'), ('TW', 'Tollywood'), ('AM', 'Animated')], default='HW', max_length=2)),
                ('user', models.ForeignKey(on_delete=builtins.callable, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
