# Generated by Django 3.0.6 on 2020-05-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproduct',
            old_name='product_name',
            new_name='movie_name',
        ),
    ]
