# Generated by Django 3.0.6 on 2020-05-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_details', '0002_auto_20200522_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='category',
            field=models.CharField(choices=[('hollywood', 'Hollywood'), ('bollywood', 'Bollywood'), ('tollywood', 'Tollywood'), ('animated', 'Animated')], default='hollywood', max_length=12),
        ),
    ]
