# Generated by Django 3.0.6 on 2020-05-24 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies_details', '0003_auto_20200523_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='country',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addproduct',
            name='genre',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
    ]
