# Generated by Django 3.0.6 on 2020-05-24 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_details', '0005_addlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='addlinks',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='movies_details.AddProduct'),
            preserve_default=False,
        ),
    ]
