# Generated by Django 3.0.6 on 2020-05-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_details', '0007_auto_20200524_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addlinks',
            old_name='user',
            new_name='author',
        ),
    ]
