# Generated by Django 3.0.6 on 2020-05-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_details', '0008_auto_20200524_0806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddLinks',
        ),
    ]
