# Generated by Django 3.0.6 on 2020-05-25 10:48

import builtins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies_details', '0009_delete_addlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('user', models.OneToOneField(on_delete=builtins.callable, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
